version: "3.7"
services:
  item-app:
    image: dhanifudin/item-app:v1
    restart: on-failure
    ports:
      - 80:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production
      DB_HOST: item-db
  item-db:
    image: mongo:3
    restart: on-failure
    volumes:
      - app-db:/data/db
volumes:
  app-db: