name: Build karsajobs image
on:
  push:
    branches: [karsajobs]
  pull_request:
    branches: [karsajobs]
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hadolint
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run tests
        run: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    runs-on: ubuntu-latest
    needs: [lint-dockerfile, test-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/karsajobs:latest