name: Build karsajobs-ui image
on:
  push:
    branches: [karsajobs-ui]
  pull_request:
    branches: [karsajobs-ui]
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hadolint
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile
  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    needs: [lint-dockerfile, test-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/karsajobs-ui:latest